version: "3.9"

services:
  api-service:
    container_name: API
    build:
        dockerfile: SecureWebAPI/Dockerfile
        context: .
    ports:
      - 3000:8080
  jwt-service:
    container_name: JWTService
    build:
        dockerfile: JWT/Dockerfile
        context: .
    ports:
      - 3001:8080
